### ISSUE TITLE
Could not establish trust relationship for the SSL/TLS secure channel

### ISSUE THREAD

**Issue by adamfisher** [FubarDevelopment/restsharp.portable#43]
When attempting to hit a rest service with RestSharp.Portable I get an error related to the SSL certificate. I have been able to successfully hit other web services in the past using this library.

It looks like the [common answer](http://stackoverflow.com/questions/10397736/restsharp-ignore-ssl-errors) has been to use ServicePointManager to validate the certificates yourself but that API doesn't appear to be available in a profile 78 PCL. Is there anything that RestSharp.Portable exposes to allow filtering/validating certificates?

```csharp
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: A
n error occurred while sending the request. ---> System.Net.WebException: The underlying connection
was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Secur
ity.Authentication.AuthenticationException: The remote certificate is invalid according to the valid
ation procedure.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RestSharp.Portable.RestClient.<ExecuteRequest>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RestSharp.Portable.RestClient.<Execute>d__8`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at EulaWebServiceTest.Program.Main(String[] args) in c:\Users\afishe\Desktop\EulaWebServiceTest\P
rogram.cs:line 26
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the
request. ---> System.Net.WebException: The underlying connection was closed: Could not establish tru
st relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationEx
ception: The remote certificate is invalid according to the validation procedure.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RestSharp.Portable.RestClient.<ExecuteRequest>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RestSharp.Portable.RestClient.<Execute>d__8`1.MoveNext()<---
```

**Comment by adamfisher** [comment]
It looks like ServicePointManager can be used in both Xamarin.iOS and Xamarin.Android but not the PCL. I'll create some initialization code on each platform  and see if that fixes the issue.

http://stackoverflow.com/questions/28629989/ignore-ssl-certificate-errors-in-xamarin-forms-pcl

**Comment by fubar-coder** [comment]
You're right regarding the certificates. However, you have two choices:

1. Override the SSL handling globally using the [ServicePointManager](https://msdn.microsoft.com/library/system.net.servicepointmanager.aspx)
2. Use a custom ```IHttpClientFactory``` which is then assigned to ```RestClient.HttpClientFactory```

When you use option 2, then it's easier when you just override ```DefaultHttpClientFactory.CreateMessageHandler``` instead of implementing ```IHttpClientFactory``` yourself. You can use something like [WinRtHttpClientHandler](https://github.com/onovotny/WinRtHttpClientHandler) for WinRT platforms and other solutions for the other platforms.

TBH: I'd go for option 1, because it's the easiest way to handle this kind of problem. You should only use option 2 when you require certificate pinning.

Please close this ticket if you was able to solve your certificate problem.

**Comment by adamfisher** [comment]
Thanks for the response. I ended up going with option 1. I added the code below to each platform specific project and was back in business...

```csharp
ServicePointManager.ServerCertificateValidationCallback += 
(sender, certificate, chain, errors) => true;
```
