### ISSUE TITLE
System.Threading.Tasks.TaskCanceledException: A task was canceled.

### ISSUE THREAD

**Issue by bilal-fazlani** [FubarDevelopment/restsharp.portable#49]
The following code throws exception with message: 
`Caused by: md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.Threading.Tasks.TaskCanceledException: A task was canceled.`
        
        protected override async void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);

            if (!IsConnectedToService())
            {
                throw new Exception("cant connect to service");
            }

            base.OnCreate(bundle);

            // Set our view from the "main" layout resource
            SetContentView(Resource.Layout.Main);

            ListView carListView = FindViewById<ListView>(Resource.Id.carlistView);

            List<string> cars = (await _client.GetAllAsync()).Select(x=>x.Model).ToList();

            _adapter = new ArrayAdapter(
                this,
                Android.Resource.Layout.SimpleListItem1,
                cars);

            carListView.Adapter = _adapter;
        }

---------------
        public async Task<List<T>> GetAllAsync()
        {
            RestRequest request = new RestRequest();

            var response = await _restClient.Execute<List<T>>(request);

            return response.Data;
        }

This is full stack trace:

```
11-11 13:16:03.774 E/AndroidRuntime(  966): FATAL EXCEPTION: main
11-11 13:16:03.774 E/AndroidRuntime(  966): Process: AndroidConsumer.AndroidConsumer, PID: 966
11-11 13:16:03.774 E/AndroidRuntime(  966): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
11-11 13:16:03.774 E/AndroidRuntime(  966): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
11-11 13:16:03.774 E/AndroidRuntime(  966): Caused by: java.lang.reflect.InvocationTargetException
11-11 13:16:03.774 E/AndroidRuntime(  966): 	at java.lang.reflect.Method.invoke(Native Method)
11-11 13:16:03.774 E/AndroidRuntime(  966): 	at java.lang.reflect.Method.invoke(Method.java:372)
11-11 13:16:03.774 E/AndroidRuntime(  966): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
11-11 13:16:03.774 E/AndroidRuntime(  966): 	... 1 more
11-11 13:16:03.774 E/AndroidRuntime(  966): Caused by: md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.Threading.Tasks.TaskCanceledException: A task was canceled.
11-11 13:16:03.774 E/AndroidRuntime(  966): at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/builder/data/lanes/2058/96592261/source/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:61
11-11 13:16:03.774 E/AndroidRuntime(  966): at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (object) [0x00000] in /Users/builder/data/lanes/2058/96592261/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1006
11-11 13:16:03.774 E/AndroidRuntime(  966): at Android.App.SyncContext/<Post>c__AnonStorey0.<>m__0 () [0x00000] in /Users/builder/data/lanes/2058/96592261/source/monodroid/src/Mono.Android/src/Android.App/SyncContext.cs:18
11-11 13:16:03.774 E/AndroidRuntime(  966): at Java.Lang.Thread/RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/2058/96592261/source/monodroid/src/Mono.Android/src/Java.Lang/Thread.cs:36
11-11 13:16:03.774 E/AndroidRuntime(  966): at Java.Lang.IRunnableInvoker.n_Run (intptr,intptr) [0x00009] in /Users/builder/data/lanes/2058/96592261/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Java.Lang.IRunnable.cs:71
11-11 13:16:03.774 E/AndroidRuntime(  966): at (wrapper dynamic-method) object.a29135ab-f122-4aad-a167-ff222dc57614 (intptr,intptr) <IL 0x00011, 0x0001f>
11-11 13:16:03.774 E/AndroidRuntime(  966): 
11-11 13:16:03.774 E/AndroidRuntime(  966): 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
11-11 13:16:03.774 E/AndroidRuntime(  966): 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
11-11 13:16:03.774 E/AndroidRuntime(  966): 	at android.os.Handler.handleCallback(Handler.java:739)
11-11 13:16:03.774 E/AndroidRuntime(  966): 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-11 13:16:03.774 E/AndroidRuntime(  966): 	at android.os.Looper.loop(Looper.java:135)
11-11 13:16:03.774 E/AndroidRuntime(  966): 	at android.app.ActivityThread.main(ActivityThread.java:5253)
11-11 13:16:03.774 E/AndroidRuntime(  966): 	... 4 more
11-11 13:21:03.825 I/Process (  966): Sending signal. PID: 966 SIG: 9
```

**Comment by bilal-fazlani** [comment]
**This is only happening in xamarin.android application.** I tested with console application and a wpf application too and it seems to be working on those platforms.

**Comment by bilal-fazlani** [comment]
This is happening if I await anything. So it doesn't seem to be an issue of this library. Hence closing.
